### ISSUE TITLE
SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by rolance** [shubhank-srivastava/meanjs-module-generator#1]
I'm quite new to javascript/node/mean. Am I doing something wrong? 'yo-mean' is my project folder. Thanks.

C:\Users\LHM\Documents\Visual Studio 2015\Projects\ndolc-flashcards\yo-mean>node modgen articles flashcards
C:\Users\LHM\Documents\Visual Studio 2015\Projects\ndolc-flashcards\yo-mean\modgen.js:5
<!DOCTYPE html>
^

SyntaxError: Unexpected token <
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

C:\Users\LHM\Documents\Visual Studio 2015\Projects\ndolc-flashcards\yo-mean>

**Comment by shubhank-srivastava** [comment]
@rolance I don't think anything is wrong with your command. Also modgen.js doesn't contain anything as <!DOCTYPE html> so I'm confused by looking at this error. I need more info on how to generate this error.
